Fixed crash: password and user should be escaped with percent charact…
vapor-community/mongo-driver pull request #20
Opened 2016-11-01 05:36 UTC by sebastienwindal

…ers.

2016-11-01 15:39 UTC, tanner0101 requested changes

2016-11-01 15:39 UTC, tannernelson commented on Sources/MongoDriver.swift
> +        let escapedPassword = password.addingPercentEncoding(withAllowedCharacters: .urlHostAllowed)!
Can we throw an error instead of implicitly unwrapping the password?

2016-11-04 15:07 UTC, tanner0101 approved these changes

2016-11-04 15:07 UTC, tannernelson commented
Is this good to merge?

2016-11-04 17:01 UTC, sebastienwindal commented
yes it is!

2016-11-04 19:47 UTC, tannernelson commented
Cool. Thanks :)

2016-11-04 19:47 UTC, merged