Mongokitten4/Mongo-Drive update
vapor-community/mongo-driver pull request #32
Opened 2017-04-14 18:44 UTC by cam25

Updated Mongo-Drive to be compatible with latest version of Fluent/Vapor

2017-04-14 20:57 UTC, vzsg requested changes
I added a few observations of mine, but this is by no means conclusive.

2017-04-14 20:57 UTC, vzsg commented on Sources/Query+MongoKitten.swift
> +        return .and(aqts as! [AQT])
Don't use a force cast here!
Instead, try rewriting the above line to:

```swift
let aqts = try filters.flatMap { try $0.wrapped?.makeAQT() } // aqts is now an [AQT]
```

2017-04-14 20:57 UTC, vzsg commented on Sources/MongoDriver.swift
> +    public /// The naming convetion to use for foreign
What's up with this `public` keyword here?

2017-04-14 20:57 UTC, vzsg commented on Sources/Filter+MongoKitten.swift
> +            let aqts = try filters.map { try $0.wrapped?.makeAQT()}
Same as the other, use flatMap instead of force casting.

2017-04-14 20:57 UTC, vzsg commented on Sources/Filter+MongoKitten.swift
> +                query = .containsElement(key: key, match: val.bson as! AQT)
Are you sure that this is the right way?

2017-04-22 08:52 UTC, cam25 commented on Sources/MongoDriver.swift
> +    public /// The naming convetion to use for foreign
Should be removed. Not serving any purpose here.

2017-04-22 08:52 UTC, cam25 commented on Sources/Query+MongoKitten.swift
> +        return .and(aqts as! [AQT])
Will update, thanks!

2017-04-22 09:05 UTC, cam25 commented on Sources/Filter+MongoKitten.swift
> +            let aqts = try filters.map { try $0.wrapped?.makeAQT()}
Done

2017-04-22 11:59 UTC, Joannis commented
I think we should remove the `.swift-version` file by now

2017-04-22 12:03 UTC, Joannis commented
This driver will be Swift 3.1 and Vapor 2 only. So this PR will at least need to be merged after Vapor 2 gets out of Beta and MongoKitten 4 has adapted to that.

2017-04-22 13:13 UTC, vzsg commented
There's a lot of work before this can be released as a beta in the first place. But if it starts working, I don't see an issue – all Vapor repos have their beta versions in the master branch.

2018-10-26 08:28 UTC, closed without merging