Add support for subset queries
vapor-community/mongo-driver pull request #35
Opened 2017-07-15 21:31 UTC by jordoh

This adds support for subset queries, i.e.:

```
query.filter(.subset("_id", .in, ids))
```
and
```
query.filter(.subset("_id", .notIn, ids))
```

2017-07-19 19:59 UTC, Joannis requested changes
I'd love a unit test to be added to cover this. Calling fluent with a subset query which then results in the expected MongoDB behaviour. Looks good otherwise

2017-07-22 21:46 UTC, jordoh commented
Hi @Joannis - I've pushed with tests for `.in` and `.notIn`, but have a couple questions:

- I added a `Tester+Subset.swift` to match the pattern of existing tests, but it looks like that might belong in Fluent itself. Is it reasonable to include that here?

- I'm seeing the existing `testSoftDelete` fail locally on master (at ef1f069), and on CircleCI for this branch - it that expected? It doesn't look like that failed on CircleCI for ef1f069 in this repo.

2017-07-23 10:20 UTC, Joannis commented
Hello @jordoh :)

First of all, thanks for the PR 👍 
The unit tests could be in Fluent, I think that wouldn't be unreasonable. @tanner0101 , what do you think?

I just noticed that, too. It's not your code that broke it, I'm certain of that.

I'll leave the merge and tag up to @tanner0101 , and if he thinks this test needs to be moved to Fluent that could be done after the merge :)

Thanks again :)

2017-08-22 08:35 UTC, Joannis approved these changes

2017-08-28 08:49 UTC, merged