update dependencies
vapor-community/mongo-driver pull request #7
Opened 2016-09-17 10:08 UTC by amreshkumar

Changes:
1. update dependencies for Fluent and MongoKitten to latest version
2. add Provider for MongoDB (similar to SQL)

2016-09-19 17:30 UTC, tannernelson commented on Sources/Provider.swift
> +import Vapor
How is Vapor being included if this package doesn't depend on it? The `mongo-driver`s job should be mapping Fluent queries to Mongo. The `mongo-provider` is responsible for implementing the `Vapor.Provider.`

2016-09-19 17:30 UTC, tanner0101 requested changes

2016-09-20 07:34 UTC, amreshkumar commented on Sources/Provider.swift
> +import Vapor
I understand what you say. I'll close the pull request and resubmit it. Thanks.

2016-09-20 07:34 UTC, closed without merging

2016-09-20 08:11 UTC, amreshkumar commented on Sources/Provider.swift
> +import Vapor
I don't see a mongo-provider repo here. Hope we can get one.